import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { TailwindIndicator } from "@/components/tailwind-indicator";
import { ReactQueryClientProvider } from "@/providers/react-query-provider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body className={GeistSans.className}>
          {children}
          <Toaster position="top-right" />
          <TailwindIndicator />
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
